### ISSUE TITLE
[RFC]: Archive project

### ISSUE THREAD

**Issue by Ocramius** [laminas/laminas-twitter#33]
## RFC

Twitter is gradually (but steadily) jumping off a high cliff.

The API will no longer be accessible for free starting 2023-02-09, and therefore there is no way we can help maintaining compatibility with it, including security support.

This library should therefore be archived.

/cc @laminas/technical-steering-committee 

| Q                   | A      |
| ------------------- | ------ |
| Proposed Version(s) | 3.8.0 |
| BC Break?           | Yes |

**Comment by weierophinney** [comment]
The code will still be usable by somebody with a license key... but, as you note, we cannot do any integration testing or troubleshooting unless we _also_ have a license. While we could pay for one out of the foundation funds... it seems like we shouldn't encourage usage of the fascist platform, either. So I'm :+1: .

**Comment by boesing** [comment]
🔥

**Comment by samsonasik** [comment]
This probably may keep working, ref https://www.theverge.com/2023/2/5/23586577/elon-musk-bots-good-content-twitters-api-free

**Comment by samsonasik** [comment]
Twitter API free acesss is 1500 tweets per month https://twitter.com/TwitterDev/status/1623467618400374784?s=20&t=f018R2cWzaN1OSak5JV9jQ

**Comment by internalsystemerror** [comment]
But will it stay that way 😟

**Comment by weierophinney** [comment]
Unless that number hits 5 digits, I still don't see this as being viable. Any introduction of E2E or integration testing here would blow through that number very quickly. Additionally, for any developers who want to provide patches, they'd need to sign up in order to run tests locally before pushing a PR AND, if they do, likely would be using from the allotment they already use for whatever bot(s) they run with that same account, reducing their overall ability to use the bot. ON TOP OF THAT, my understanding is that these free keys would be write-only - you could do things like post statuses, but not _retrieve_ any - and that latter would be necessary in any E2E scenarios to determine if it worked successfully.

If they were just doing rate limiting (like github does), this would be more viable; the fact that it's a monthly allowance, and it's so low, is what makes it no good for developers.

**Comment by internalsystemerror** [comment]
The unpredictability of these policies makes me say let's just avoid altogether, we could easily find ourselves having wasted a lot of time and effort due to another policy change.

**Comment by samsonasik** [comment]
+1 for archiving it then 👍

**Comment by Ocramius** [comment]
We'd probably need a patch to adjust `README.md` and the documentation, and then we can call the shot on it.
